package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

const rustIndexFileTemplate = `// Generated by Lisette bindgen. DO NOT EDIT.

use std::collections::HashMap;
use std::sync::LazyLock;

use crate::Target;

static GO_STDLIB_COMMON: LazyLock<HashMap<&str, &str>> = LazyLock::new(|| {
    HashMap::from([
%s    ])
});

%s
static GO_STDLIB_PACKAGE_TARGETS: LazyLock<HashMap<&str, &[(&str, &str)]>> =
    LazyLock::new(|| {
        HashMap::from([
%s        ])
    });

pub fn get_go_stdlib_typedef(package: &str, target: Target) -> Option<&'static str> {
    if !is_available_on(package, target) {
        return None;
    }
    if let Some(source) = lookup_in_overlay(target, package) {
        return Some(source);
    }
    GO_STDLIB_COMMON.get(package).copied()
}

pub fn get_go_stdlib_packages(target: Target) -> Vec<&'static str> {
    let mut packages: Vec<&'static str> = GO_STDLIB_COMMON
        .keys()
        .copied()
        .filter(|pkg| is_available_on(pkg, target))
        .collect();
    if let Some(overlay) = overlay_for(target) {
        packages.extend(overlay.keys().copied());
    }
    packages.sort();
    packages
}

pub fn get_go_stdlib_package_targets(
    package: &str,
) -> Option<&'static [(&'static str, &'static str)]> {
    GO_STDLIB_PACKAGE_TARGETS.get(package).copied()
}

fn is_available_on(package: &str, target: Target) -> bool {
    match GO_STDLIB_PACKAGE_TARGETS.get(package) {
        Some(targets) => targets
            .iter()
            .any(|(goos, goarch)| *goos == target.goos && *goarch == target.goarch),
        None => true,
    }
}

fn lookup_in_overlay(target: Target, package: &str) -> Option<&'static str> {
    overlay_for(target).and_then(|overlay| overlay.get(package).copied())
}

fn overlay_for(target: Target) -> Option<&'static HashMap<&'static str, &'static str>> {
    match (target.goos, target.goarch) {
%s        _ => None,
    }
}
`

func generateRustIndexFile(outDir string, partition partitioned, targets []Target) error {
	srcDir := filepath.Join(outDir, "..", "src")
	if _, err := os.Stat(srcDir); os.IsNotExist(err) {
		return nil
	}

	commonPaths := sortedKeys(partition.common)
	commonEntries := buildEntries(commonPaths, nil)

	// Invert variants into per-target entries pointing at canonical files.
	perTarget := make(map[Target]map[string]Target)
	for pkgPath, variants := range partition.variants {
		for _, v := range variants {
			for _, t := range v.targets {
				if perTarget[t] == nil {
					perTarget[t] = make(map[string]Target)
				}
				perTarget[t][pkgPath] = v.canonical
			}
		}
	}

	var overlayBlocks strings.Builder
	var matchArms strings.Builder
	for _, target := range targets {
		entries := perTarget[target]
		if len(entries) == 0 {
			continue
		}
		paths := make([]string, 0, len(entries))
		for p := range entries {
			paths = append(paths, p)
		}
		slices.Sort(paths)
		staticName := overlayStaticName(target)
		fmt.Fprintf(&overlayBlocks, "static %s: LazyLock<HashMap<&str, &str>> = LazyLock::new(|| {\n    HashMap::from([\n", staticName)
		overlayBlocks.WriteString(buildEntries(paths, entries))
		overlayBlocks.WriteString("    ])\n});\n\n")

		fmt.Fprintf(&matchArms, "        (%q, %q) => Some(&%s),\n", target.GOOS, target.GOARCH, staticName)
	}

	intendedEntries := buildIntendedEntries(partition.intendedTargets)

	content := fmt.Sprintf(rustIndexFileTemplate,
		commonEntries,
		overlayBlocks.String(),
		intendedEntries,
		matchArms.String(),
	)

	rustFilePath := filepath.Join(srcDir, "go_modules.rs")
	if err := os.WriteFile(rustFilePath, []byte(content), 0644); err != nil {
		return err
	}

	fmt.Fprintf(os.Stderr, "\nGenerated: %s\n", rustFilePath)
	return nil
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	slices.Sort(keys)
	return keys
}

// buildEntries renders HashMap entries for a typedef map. When `canonical`
// is nil, paths point at suffixless files (the common map). Otherwise each
// entry points at the canonical target's file for that package.
func buildEntries(pkgPaths []string, canonical map[string]Target) string {
	var b strings.Builder
	for _, pkgPath := range pkgPaths {
		suffix := ""
		if t, ok := canonical[pkgPath]; ok {
			suffix = "_" + t.Suffix()
		}
		fmt.Fprintf(&b,
			"        (%q, include_str!(\"../typedefs/%s%s.d.lis\")),\n",
			pkgPath, pkgPath, suffix,
		)
	}
	return b.String()
}

func buildIntendedEntries(intended map[string][]Target) string {
	pkgs := make([]string, 0, len(intended))
	for pkg := range intended {
		pkgs = append(pkgs, pkg)
	}
	slices.Sort(pkgs)

	var b strings.Builder
	for _, pkg := range pkgs {
		var pairs strings.Builder
		for i, t := range intended[pkg] {
			if i > 0 {
				pairs.WriteString(", ")
			}
			fmt.Fprintf(&pairs, "(%q, %q)", t.GOOS, t.GOARCH)
		}
		fmt.Fprintf(&b, "            (%q, &[%s][..]),\n", pkg, pairs.String())
	}
	return b.String()
}

func overlayStaticName(target Target) string {
	return "GO_STDLIB_" + strings.ToUpper(target.GOOS) + "_" + strings.ToUpper(target.GOARCH)
}
