mod bool_literal_comparison;
mod double_negation;
mod dup_arg;
mod duplicate_cutset;
mod duplicate_logical_operand;
mod empty_match_arm;
mod excess_parens_on_condition;
mod helpers;
mod identical_if_branches;
mod identical_match_arms;
mod invisible_in_string;
mod loop_runs_once;
mod lost_query_mutation;
mod manual_compound_assignment;
mod manual_map;
mod manual_unwrap_or;
mod match_literal_collection;
mod naming;
mod redundant_closure;
mod redundant_pattern_matching;
mod replaceable_with_zero_fill;
mod rest_only_slice_pattern;
mod self_assignment;
mod self_comparison;
mod single_arm_match;
mod uninterpolated_fstring;
mod unnecessary_bool;
mod unnecessary_range_loop;
mod unnecessary_raw_string;
mod unnecessary_return;
mod unsigned_comparison;
mod verbose_failure_propagation;
mod waitgroup_add_in_task;

pub use bool_literal_comparison::check_bool_literal_comparison;
pub use double_negation::check_double_negation;
pub use dup_arg::check_dup_arg;
pub use duplicate_cutset::check_duplicate_cutset;
pub use duplicate_logical_operand::check_duplicate_logical_operand;
pub use empty_match_arm::check_empty_match_arm;
pub use excess_parens_on_condition::check_excess_parens_on_condition;
pub use identical_if_branches::check_identical_if_branches;
pub use identical_match_arms::check_identical_match_arms;
pub use invisible_in_string::{
    check_invisible_in_string_expression, check_invisible_in_string_pattern,
};
pub use loop_runs_once::check_loop_runs_once;
pub use lost_query_mutation::check_lost_query_mutation;
pub use manual_compound_assignment::check_manual_compound_assignment;
pub use manual_map::check_manual_map;
pub use manual_unwrap_or::check_manual_unwrap_or;
pub use match_literal_collection::check_match_literal_collection;
pub use naming::{check_expression_naming, check_pattern_naming};
pub use redundant_closure::check_redundant_closure;
pub use redundant_pattern_matching::check_redundant_pattern_matching;
pub use replaceable_with_zero_fill::check_replaceable_with_zero_fill;
pub use rest_only_slice_pattern::check_rest_only_slice_pattern;
pub use self_assignment::check_self_assignment;
pub use self_comparison::check_self_comparison;
pub use single_arm_match::check_single_arm_match;
pub use uninterpolated_fstring::check_uninterpolated_fstring;
pub use unnecessary_bool::check_unnecessary_bool;
pub use unnecessary_range_loop::check_unnecessary_range_loop;
pub use unnecessary_raw_string::{
    check_unnecessary_raw_string_expression, check_unnecessary_raw_string_pattern,
};
pub use unnecessary_return::check_unnecessary_return;
pub use unsigned_comparison::check_unsigned_comparison;
pub use verbose_failure_propagation::check_verbose_failure_propagation;
pub use waitgroup_add_in_task::check_waitgroup_add_in_task;
