mod almost_swapped;
mod bad_bit_mask;
mod bind_instead_of_map;
mod bool_literal_comparison;
mod collapsible_if;
mod double_comparison;
mod double_negation;
mod dup_arg;
mod duplicate_cutset;
mod duplicate_logical_operand;
mod empty_match_arm;
mod equal_operands;
mod excess_parens_on_condition;
mod exit_after_defer;
mod float_cmp;
mod float_equality_without_abs;
mod goos_goarch_comparison;
mod helpers;
mod identical_if_branches;
mod identical_match_arms;
mod ineffective_bit_mask;
mod integer_division_to_zero;
mod invisible_in_string;
mod let_and_return;
mod loop_runs_once;
mod lost_cancel;
mod lost_query_mutation;
mod manual_bytes_equal;
mod manual_compound_assignment;
mod manual_equal_fold;
mod manual_filter;
mod manual_find;
mod manual_is_empty;
mod manual_map;
mod manual_map_or;
mod manual_ok_err;
mod manual_ok_or;
mod manual_option_zip;
mod manual_replace_all;
mod manual_time_since;
mod manual_time_until;
mod manual_unwrap_or;
mod map_flatten;
mod map_identity;
mod map_or_none;
mod map_unwrap_or;
mod match_as_if_let;
mod match_literal_collection;
mod match_on_bool;
mod match_single_binding;
mod naming;
mod needless_match;
mod needless_question_mark;
mod negated_equality;
mod non_negative_comparison;
mod out_of_domain;
mod redundant_closure;
mod redundant_comparison;
mod redundant_else;
mod redundant_operation;
mod redundant_pattern_matching;
mod redundant_slice_bounds;
mod redundant_sprintf;
mod regexp_in_loop;
mod replaceable_with_zero_fill;
mod rest_only_slice_pattern;
mod self_assignment;
mod self_comparison;
mod single_arm_select;
mod type_limit_comparison;
mod uninterpolated_fstring;
mod unnecessary_bool;
mod unnecessary_map_on_constructor;
mod unnecessary_min_or_max;
mod unnecessary_range_loop;
mod unnecessary_raw_string;
mod unnecessary_return;
mod unsigned_comparison;
mod verbose_failure_propagation;
mod waitgroup_add_in_task;

pub use almost_swapped::check_almost_swapped;
pub use bad_bit_mask::check_bad_bit_mask;
pub use bind_instead_of_map::check_bind_instead_of_map;
pub use bool_literal_comparison::check_bool_literal_comparison;
pub use collapsible_if::check_collapsible_if;
pub use double_comparison::check_double_comparison;
pub use double_negation::check_double_negation;
pub use dup_arg::check_dup_arg;
pub use duplicate_cutset::check_duplicate_cutset;
pub use duplicate_logical_operand::check_duplicate_logical_operand;
pub use empty_match_arm::check_empty_match_arm;
pub use equal_operands::check_equal_operands;
pub use excess_parens_on_condition::check_excess_parens_on_condition;
pub use exit_after_defer::check_exit_after_defer;
pub use float_cmp::check_float_cmp;
pub use float_equality_without_abs::check_float_equality_without_abs;
pub use goos_goarch_comparison::check_goos_goarch_comparison;
pub use identical_if_branches::check_identical_if_branches;
pub use identical_match_arms::check_identical_match_arms;
pub use ineffective_bit_mask::check_ineffective_bit_mask;
pub use integer_division_to_zero::check_integer_division_to_zero;
pub use invisible_in_string::{
    check_invisible_in_string_expression, check_invisible_in_string_pattern,
};
pub use let_and_return::check_let_and_return;
pub use loop_runs_once::check_loop_runs_once;
pub use lost_cancel::check_lost_cancel;
pub use lost_query_mutation::check_lost_query_mutation;
pub use manual_bytes_equal::check_manual_bytes_equal;
pub use manual_compound_assignment::check_manual_compound_assignment;
pub use manual_equal_fold::check_manual_equal_fold;
pub use manual_filter::check_manual_filter;
pub use manual_find::check_manual_find;
pub use manual_is_empty::check_manual_is_empty;
pub use manual_map::check_manual_map;
pub use manual_map_or::check_manual_map_or;
pub use manual_ok_err::check_manual_ok_err;
pub use manual_ok_or::check_manual_ok_or;
pub use manual_option_zip::check_manual_option_zip;
pub use manual_replace_all::check_manual_replace_all;
pub use manual_time_since::check_manual_time_since;
pub use manual_time_until::check_manual_time_until;
pub use manual_unwrap_or::check_manual_unwrap_or;
pub use map_flatten::check_map_flatten;
pub use map_identity::check_map_identity;
pub use map_or_none::check_map_or_none;
pub use map_unwrap_or::check_map_unwrap_or;
pub use match_as_if_let::check_match_as_if_let;
pub use match_literal_collection::check_match_literal_collection;
pub use match_on_bool::check_match_on_bool;
pub use match_single_binding::check_match_single_binding;
pub use naming::{check_expression_naming, check_pattern_naming};
pub use needless_match::check_needless_match;
pub use needless_question_mark::check_needless_question_mark;
pub use negated_equality::check_negated_equality;
pub use non_negative_comparison::check_non_negative_comparison;
pub use out_of_domain::check_out_of_domain_value;
pub use redundant_closure::check_redundant_closure;
pub use redundant_comparison::check_redundant_comparison;
pub use redundant_else::check_redundant_else;
pub use redundant_operation::check_redundant_operation;
pub use redundant_pattern_matching::check_redundant_pattern_matching;
pub use redundant_slice_bounds::check_redundant_slice_bounds;
pub use redundant_sprintf::check_redundant_sprintf;
pub use regexp_in_loop::check_regexp_in_loop;
pub use replaceable_with_zero_fill::check_replaceable_with_zero_fill;
pub use rest_only_slice_pattern::check_rest_only_slice_pattern;
pub use self_assignment::check_self_assignment;
pub use self_comparison::check_self_comparison;
pub use single_arm_select::check_single_arm_select;
pub use type_limit_comparison::check_type_limit_comparison;
pub use uninterpolated_fstring::check_uninterpolated_fstring;
pub use unnecessary_bool::check_unnecessary_bool;
pub use unnecessary_map_on_constructor::check_unnecessary_map_on_constructor;
pub use unnecessary_min_or_max::check_unnecessary_min_or_max;
pub use unnecessary_range_loop::check_unnecessary_range_loop;
pub use unnecessary_raw_string::{
    check_unnecessary_raw_string_expression, check_unnecessary_raw_string_pattern,
};
pub use unnecessary_return::check_unnecessary_return;
pub use unsigned_comparison::check_unsigned_comparison;
pub use verbose_failure_propagation::check_verbose_failure_propagation;
pub use waitgroup_add_in_task::check_waitgroup_add_in_task;
